// Demo timeline builder — narration-first timing algorithm
// Computes timestamps for zoom, narration, action, and step boundaries

import type { DemoScript, DemoStep } from './demo-script.js';

// ─── Types ──────────────────────────────────────────────────

export interface StepTiming {
  stepIndex: number;
  stepStart: number;       // ms — when this step begins
  zoomStart: number;       // ms — when zoom begins
  zoomEnd: number;         // ms — when zoom settles
  narrationStart: number;  // ms — when narration audio starts
  narrationEnd: number;    // ms — when narration audio ends
  actionStart: number;     // ms — when UI action starts
  actionEnd: number;       // ms — when UI action finishes
  stepEnd: number;         // ms — when step is fully done
}

export interface DemoTimeline {
  steps: StepTiming[];
  totalDurationMs: number;
}

export interface NarrationManifest {
  narration: {
    scenes: Array<{
      elements: Array<{
        id: string;
        audio_file?: string;
        audio_duration_ms?: number;
      }>;
    }>;
  };
}

// ─── Constants ──────────────────────────────────────────────

const ACTION_CURSOR_MOVE_MS = 500;   // cursor animation to target
const ACTION_CLICK_MS = 200;          // click press animation
const ACTION_FILL_CHAR_MS = 60;       // default typing speed
const ACTION_SCROLL_MS = 600;         // scroll animation
const ACTION_HOVER_MS = 300;          // hover settle time
const NARRATION_ACTION_OVERLAP = 200; // narration starts, action follows shortly after

// ─── Public API ─────────────────────────────────────────────

/**
 * Build the demo timeline from script + narration manifest.
 *
 * Algorithm (narration-first):
 * 1. stepStart = previous stepEnd + gapBetweenSteps
 * 2. zoomStart = stepStart
 * 3. narrationStart = stepStart + zoomTransitionMs
 * 4. actionStart = narrationStart + NARRATION_ACTION_OVERLAP
 * 5. stepEnd = max(narrationEnd, actionEnd) + waitAfter
 */
export function buildDemoTimeline(
  script: DemoScript,
  manifest: NarrationManifest,
): DemoTimeline {
  const steps: StepTiming[] = [];
  let cursor = 0; // current time in ms

  for (let i = 0; i < script.steps.length; i++) {
    const step = script.steps[i];
    const narrationDuration = getNarrationDuration(manifest, i, step);
    const actionDuration = getActionDuration(step);

    // Step start
    const stepStart = cursor;

    // Zoom starts immediately at step start
    const zoomStart = stepStart;
    const zoomEnd = zoomStart + script.zoomTransitionMs;

    // Narration starts after zoom settles
    const narrationStart = zoomEnd;
    const narrationEnd = narrationStart + narrationDuration;

    // Action starts shortly after narration begins
    const actionStart = narrationStart + NARRATION_ACTION_OVERLAP;
    const actionEnd = actionStart + actionDuration;

    // Step ends after both narration and action are done, plus any extra wait
    const waitAfter = step.waitAfter ?? 300;
    const stepEnd = Math.max(narrationEnd, actionEnd) + waitAfter;

    steps.push({
      stepIndex: i,
      stepStart,
      zoomStart,
      zoomEnd,
      narrationStart,
      narrationEnd,
      actionStart,
      actionEnd,
      stepEnd,
    });

    // Next step starts after gap
    cursor = stepEnd + script.gapBetweenSteps;
  }

  const totalDurationMs = steps.length > 0 ? steps[steps.length - 1].stepEnd : 0;

  return { steps, totalDurationMs };
}

// ─── Helpers ────────────────────────────────────────────────

function getNarrationDuration(
  manifest: NarrationManifest,
  stepIndex: number,
  step: DemoStep,
): number {
  // Try to get actual duration from manifest (generated by narration_generator.py)
  const scene = manifest.narration?.scenes?.[stepIndex];
  const element = scene?.elements?.[0];
  if (element?.audio_duration_ms) {
    return element.audio_duration_ms;
  }

  // Fallback: estimate ~400ms per word (= 150 WPM, natural speech pace)
  const wordCount = step.narration.split(/\s+/).length;
  return wordCount * 400;
}

function getActionDuration(step: DemoStep): number {
  switch (step.action) {
    case 'click':
      return ACTION_CURSOR_MOVE_MS + ACTION_CLICK_MS;

    case 'fill': {
      const charCount = (step.value ?? '').length;
      const charSpeed = step.typingSpeed ?? ACTION_FILL_CHAR_MS;
      return ACTION_CURSOR_MOVE_MS + ACTION_CLICK_MS + (charCount * charSpeed);
    }

    case 'scroll':
      return ACTION_SCROLL_MS;

    case 'hover':
      return ACTION_CURSOR_MOVE_MS + ACTION_HOVER_MS;

    case 'navigate':
      return 2000; // page load time estimate

    case 'wait':
      return step.waitAfter ?? 1000;

    case 'none':
    default:
      return 0;
  }
}
